<template>
  <div>
    <header>
      <h2>Total portfolio value : £ {{ formatPrice(totalBalance) }}</h2>
    </header>
  </div>
</template>

<script>
export default {
  name: "PortfolioTotalValue",
  data() {
    return {
      portfolio: "",
      tickerList: {},
      query:"",
      latestPrice:0,
      stockTimeSeries:{},
      totalBalance: 0
    };
  },
  mounted: function() {
    this.totalPrice();
  },
  methods: {
    //function used for formatting float numbers to two decimal digits copy paste from stack overflow dont ask me more
    formatPrice(value) {
        let val = (value/1).toFixed(2).replace(',', '.')
        return val.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")
    },
    retrieveTickerList: function() {
      /*we have 2 asynchronous requests :
      one to retrieve the data of our local express service(portfolio)
      and one nested, to retrieve the latest price for our portfolio from the remote service
      The first async with retrieve the stock symbol and the quantity of the stock
      If we have more entries of the same stock it will add the quantities.
      It will use the stock symbol to retrieve the latest price from the external api and then multiply the price
      by the quantity.
      At the end it will add the values of all the stocks to the totalBalance.
      */
      const request = async () => {
        const response = await fetch(
          "http://localhost:3000/api/shares_portfolio"
        );

        /*The await call waits for the response of the fetch to become available before assigning the value to 
        this.portfolio. Without the await this.portofolio is undefined and the execution fails before 
        the value becomes availiable. The excecution of the rest of code will be hallted until the response has been 
        completed.
        */
        this.portfolio = await response.json();
        for (var stock in this.portfolio) {
          const stockSymbol = this.portfolio[stock].ticker;
          if( typeof this.tickerList[stockSymbol] == 'undefined'){
            //if the stock does not exists in tickerList hash we add it 
            this.tickerList[stockSymbol] = parseInt(this.portfolio[stock].quantity);
          }else{
            //if the stock exists already in tickerList hash from a previous entry , we add the current quantity 
           // with the previous quantity
            this.tickerList[stockSymbol] = parseInt(this.tickerList[stockSymbol])+ parseInt(this.portfolio[stock].quantity);
          }
        }
        //get all the symbols of our stocks in an array 
        const tickers = Object.keys(this.tickerList);
        console.log("tickers:"+tickers)
        /*we now iterate over the symbols of our stocks and connect to the remote api 
        to retrieve the latest price.
        */
        for (var stockId in tickers) {
          let stockId1=stockId;
          //tickers[stockId1] is the current symbol of our stock which is generated by extracting the keys from the tickerList hash 
          this.query =
            "https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=" +
            tickers[stockId1] +
            "&interval=5min&apikey=";
          const request1 = async () => {
            const response = await fetch(
              `${this.query}${process.env.VUE_APP_API_KEY}`
            );
            //this is copy paste from Stevens code to get the latest price 
            const json = await response.json();
            const stockDetails = json["Meta Data"];
            this.stockTimeSeries = json["Time Series (5min)"];
            const keys=Object.keys(this.stockTimeSeries)
            const firstKey=keys[0]
            this.latestPrice = this.stockTimeSeries[firstKey][
              "4. close"
            ];
            const stockName=tickers[stockId1];
            console.log("StockName:" + stockName +"latestPrice"+this.latestPrice+"stockAmount"+this.tickerList[stockName]);
            //this is the total Balance that is displayed 
            this.totalBalance =this.totalBalance + this.latestPrice * parseFloat(this.tickerList[stockName]);
          };
          

          request1();
        }
      };
      request();
    },
    totalPrice: function() {
      this.retrieveTickerList();
    }
  }
};
</script>




<style scoped>
/* h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
} */
</style>
